// class Autogenerated {
//   String? name;
//   String? description;
//   List<Images>? images;
//   int? quantity;
//   double? price;
//   String? category;
//   String? sId;
//   List<Null>? ratings;
//   int? iV;

//   Autogenerated(
//       {this.name,
//       this.description,
//       this.images,
//       this.quantity,
//       this.price,
//       this.category,
//       this.sId,
//       this.ratings,
//       this.iV});

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     name = json['name'];
//     description = json['description'];
//     if (json['images'] != null) {
//       images = <Images>[];
//       json['images'].forEach((v) {
//         images!.add(Images.fromJson(v));
//       });
//     }
//     quantity = json['quantity'];
//     price = json['price'];
//     category = json['category'];
//     sId = json['_id'];
//     if (json['ratings'] != null) {
//       ratings = <Null>[];
//       json['ratings'].forEach((v) {
//         ratings!.add( Null.fromJson(v));
//       });
//     }
//     iV = json['__v'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = <String, dynamic>{};
//     data['name'] = name;
//     data['description'] = description;
//     if (images != null) {
//       data['images'] = images!.map((v) => v.toJson()).toList();
//     }
//     data['quantity'] = quantity;
//     data['price'] = price;
//     data['category'] = category;
//     data['_id'] = sId;
//     if (ratings != null) {
//       data['ratings'] = ratings!.map((v) => v.toJson()).toList();
//     }
//     data['__v'] = iV;
//     return data;
//   }
// }

// class Images {
//   String? imageUrl;
//   String? publicId;
//   String? sId;

//   Images({this.imageUrl, this.publicId, this.sId});

//   Images.fromJson(Map<String, dynamic> json) {
//     imageUrl = json['imageUrl'];
//     publicId = json['publicId'];
//     sId = json['_id'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = <String, dynamic>{};
//     data['imageUrl'] = imageUrl;
//     data['publicId'] = publicId;
//     data['_id'] = sId;
//     return data;
//   }
// }
